GET http://localhost:3000/
Content-Type: application/json

###

POST http://localhost:3000/user
Content-Type: application/json

{
  "name":"felipe",
  "email":"fel@f.com"
}


###

GET http://localhost:3000/user
Content-Type: application/json


###

GET http://localhost:3000/user/8e3c6022-af01-4c31-8259-ed5e1e7f1041
Content-Type: application/json
